name: demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24.0
  - scikit-learn>=1.0.0
  - requests>=2.25.0
  - pip
  - pip:
    - openai>=1.0.0
    - neo4j>=5.0.0
    - langchain>=0.1.0
    - langchain-openai>=0.0.8
    - langchain-core>=0.1.0
    - langgraph>=0.0.40
    - sentence-transformers>=2.2.2
    - transformers>=4.21.0
    - torch>=1.12.0
    - ragatouille>=0.0.9
    - python-dotenv>=1.0.0
    - typing-extensions>=4.0.0
    - psutil>=5.8.0
    - tqdm>=4.64.0
    - pandas>=1.5.0
    - scipy>=1.9.0 